const STATES = {
  WAITING_LOCATION: 'WAITING_LOCATION',
  WAITING_SERVICE: 'WAITING_SERVICE',
  WAITING_PROVIDER: 'WAITING_PROVIDER',
  WAITING_OPTION_DATE: 'WAITING_OPTION_DATE',
  WAITING_OPTION_PERIOD: 'WAITING_OPTION_PERIOD',
  WAITING_CUSTOMER_NAME: 'WAITING_CUSTOMER_NAME',
  WAITING_CUSTOMER_PHONE: 'WAITING_CUSTOMER_PHONE'
};

const PROVIDER_IDS = {
  ANY_PROVIDER: 'any_provider'
};

const MESSAGE_KEYS = {
  BOOK: 'BOOK',
  ANY_PROVIDER: 'ANY_PROVIDER',

  SELECT_LOCATION: 'SELECT_LOCATION',
  SELECT_SERVICE: 'SELECT_SERVICE',
  SELECT_PROVIDER: 'SELECT_PROVIDER',
  SELECT_DATE: 'SELECT_DATE',

  LOCATION_SELECT_FROM_LIST: 'LOCATION_SELECT_FROM_LIST',
  SERVICE_SELECT_FROM_LIST: 'SERVICE_SELECT_FROM_LIST',
  PROVIDER_SELECT_FROM_LIST: 'PROVIDER_SELECT_FROM_LIST',
  SESSION_LOCATION_NOT_FOUND: 'SESSION_LOCATION_NOT_FOUND',

  TODAY: 'TODAY',
  TOMORROW: 'TOMORROW',
  DAY_AFTER_TOMORROW: 'DAY_AFTER_TOMORROW',
  OTHER_DATE: 'OTHER_DATE',

  UNKNOWN_COMMAND: 'UNKNOWN_COMMAND'
};