const STATES = {
  WAITING_LOCATION: 'WAITING_LOCATION',
  WAITING_SERVICE: 'WAITING_SERVICE',
  WAITING_PROVIDER: 'WAITING_PROVIDER',

  WAITING_OPTION_DATE: 'WAITING_OPTION_DATE',
  WAITING_OPTION_PERIOD: 'WAITING_OPTION_PERIOD',

  WAITING_ADD_ANOTHER_OPTION: 'WAITING_ADD_ANOTHER_OPTION',

  WAITING_CUSTOMER_NAME: 'WAITING_CUSTOMER_NAME',
  WAITING_CUSTOMER_PHONE: 'WAITING_CUSTOMER_PHONE'
};

const PROVIDER_IDS = {
  ANY_PROVIDER: 'any_provider'
};

const MESSAGE_KEYS = {
  BOOK: 'BOOK',
  ANY_PROVIDER: 'ANY_PROVIDER',

  SELECT_LOCATION: 'SELECT_LOCATION',
  SELECT_SERVICE: 'SELECT_SERVICE',
  SELECT_PROVIDER: 'SELECT_PROVIDER',
  SELECT_DATE: 'SELECT_DATE',

  LOCATION_SELECT_FROM_LIST: 'LOCATION_SELECT_FROM_LIST',
  SERVICE_SELECT_FROM_LIST: 'SERVICE_SELECT_FROM_LIST',
  PROVIDER_SELECT_FROM_LIST: 'PROVIDER_SELECT_FROM_LIST',
  SESSION_LOCATION_NOT_FOUND: 'SESSION_LOCATION_NOT_FOUND',

  TODAY: 'TODAY',
  TOMORROW: 'TOMORROW',
  DAY_AFTER_TOMORROW: 'DAY_AFTER_TOMORROW',
  OTHER_DATE: 'OTHER_DATE',

  SELECT_PERIOD: 'SELECT_PERIOD',
  MORNING: 'MORNING',
  AFTERNOON: 'AFTERNOON',
  EVENING: 'EVENING',
  DATE_SELECT_FROM_LIST: 'DATE_SELECT_FROM_LIST',

  ADD_ANOTHER_OPTION: 'ADD_ANOTHER_OPTION',
  YES: 'YES',
  NO_CONTINUE: 'NO_CONTINUE',
  PERIOD_SELECT_FROM_LIST: 'PERIOD_SELECT_FROM_LIST',
  WAITING_ADD_ANOTHER_OPTION: 'WAITING_ADD_ANOTHER_OPTION',

  START: 'START',
  SERVICES: 'SERVICES',
  PRICES: 'PRICES',
  CONTACTS: 'CONTACTS',  
  ENTER_NAME: 'ENTER_NAME',
  ENTER_PHONE: 'ENTER_PHONE',
  REQUEST_DRAFT_READY: 'REQUEST_DRAFT_READY',
  REQUEST_CREATED: 'REQUEST_CREATED',

  UNKNOWN_COMMAND: 'UNKNOWN_COMMAND'
};