const CUSTOMER_LIST_PAGE_SIZE = 10;

const CLIENT_MENUS = {
  MAIN: 'CLIENT_MAIN',
  LOCATIONS: 'CLIENT_LOCATIONS',
  SERVICES: 'CLIENT_SERVICES',
  PROVIDERS: 'CLIENT_PROVIDERS',
  DATES: 'CLIENT_DATES',
  TIMES: 'CLIENT_TIMES',
  ADD_OPTION: 'CLIENT_ADD_OPTION',
  ADD_ANOTHER_OPTION: 'CLIENT_ADD_ANOTHER_OPTION',
  NOTE: 'CLIENT_NOTE'
};

const ADMIN_MENUS = {
  MAIN: 'ADMIN_MAIN',
  APPOINTMENTS: 'ADMIN_APPOINTMENTS',
  CUSTOMERS: 'ADMIN_CUSTOMERS',
  CUSTOMER_CONFLICTS: 'ADMIN_CUSTOMER_CONFLICTS',
  PROVIDERS: 'ADMIN_PROVIDERS',
  SERVICES: 'ADMIN_SERVICES',
  LOCATIONS: 'ADMIN_LOCATIONS',
  SETTINGS: 'ADMIN_SETTINGS'
};
